src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_category;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIdCategory(): ?int
    {
        return $this->id_category;
    }

    public function setIdCategory(int $id_category): self
    {
        $this->id_category = $id_category;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }
}

src/Controller/ProductController.php
<?php


namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Product;
use App\Entity\Category;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use App\Services\UpdateManager;


/**
 * @Route("/product", name="product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/show", name="_show_all")
     */
    public function showAllProducts()
    {
        $repository = $this->getDoctrine()->getRepository(Product::class);
        $products = $repository->findAllWithNameCategories();

        return $this->render('product/show_all.html.twig', [
            'controller_name' => 'ProductController',
            'products' => $products
        ]);
    }

    /**
     * @Route("/show/{id}", name="_show", requirements={"id"="\d+"})
     * @param $id
     * @return Response
     */
    public function showProduct($id)
    {
        $repository = $this->getDoctrine()->getRepository(Product::class);
        $product = $repository->find($id);

        if (!$product) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        } else {
            return $this->render('product/show.html.twig', [
                'controller_name' => 'ProductController',
                'product' => $product,
            ]);
        }
    }

    /**
     * @Route("/add", name="_add")
     * @param Request $request
     * @param ValidatorInterface $validator
     * @param UpdateManager $updateManager
     * @return Response
     */
    public function addProduct(Request $request, ValidatorInterface $validator, UpdateManager $updateManager)
    {
        if ($request->request->has('title')) {
            $entityManager = $this->getDoctrine()->getManager();

            $product = new Product();
            $product->setTitle($request->request->get('title'));
            $product->setIdCategory($request->request->get('id_category'));
            $product->setPrice($request->request->get('price'));
            $product->setStock($request->request->get('stock'));

            $errors = $validator->validate($product);
            if (count($errors) > 0) {
                return new Response((string) $errors, 400);
            } else {
                $entityManager->persist($product);
                $entityManager->flush();

                $message = "Added a new product with the name \"" . $product->getTitle() . "\" and the identifier \"" . $product->getId() . "\"";

                $updateManager->notifyOfUpdate($message);

                return $this->render('product/access_add.html.twig', [
                    'controller_name' => 'ProductController',
                    'product' => $product,
                ]);
            }
        } else {
            $repository = $this->getDoctrine()->getRepository(Category::class);
            $categories = $repository->findAll();

            return $this->render('product/add.html.twig', [
                'controller_name' => 'ProductController',
                'categories' => $categories,
            ]);
        }
    }

    /**
     * @Route("/edit/{id}", name="_edit", requirements={"id"="\d+"})
     * @param $id
     * @param Request $request
     * @param ValidatorInterface $validator
     * @param UpdateManager $updateManager
     * @return Response
     */
    public function editProduct(Request $request, ValidatorInterface $validator, UpdateManager $updateManager, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $product = $entityManager->getRepository(Product::class)->find($id);

        if (!$product) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        } else {
            if ($request->request->has('id')) {
                $product->setTitle($request->request->get('title'));
                $product->setIdCategory($request->request->get('id_category'));
                $product->setPrice($request->request->get('price'));
                $product->setStock($request->request->get('stock'));

                $errors = $validator->validate($product);
                if (count($errors) > 0) {
                    return new Response((string) $errors, 400);
                } else {
                    $entityManager->flush();

                    $message = "Product with identifier \"" . $product->getId() . "\" has been changed";
                    $updateManager->notifyOfUpdate($message);

                    return $this->redirectToRoute('product_show', [
                        'id' => $product->getId()
                    ]);
                }
            } else {
                $repository = $this->getDoctrine()->getRepository(Category::class);
                $categories = $repository->findAll();

                return $this->render('product/edit.html.twig', [
                    'controller_name' => 'ProductController',
                    'product' => $product,
                    'categories' => $categories,
                ]);
            }
        }
    }

    /**
     * @Route("/delete/{id}", name="_delete", requirements={"id"="\d+"})
     * @param UpdateManager $updateManager
     * @param $id
     * @return Response
     */
    public function deleteProduct(UpdateManager $updateManager, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $product = $entityManager->getRepository(Product::class)->find($id);

        if (!$product) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        } else {
            $entityManager->remove($product);
            $entityManager->flush();

            $message = "Product with identifier \"" . $id . "\" has been removed";
            $updateManager->notifyOfUpdate($message);

            return $this->render('product/access_delete.html.twig', [
                'controller_name' => 'ProductController',
                'product' => $product,
            ]);
        }
    }
}

templates/product/access_add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product successfully added!{% endblock %}

{% block body %}
    <div class="alert alert-success" role="alert">
        Product "{{ product.title }}" successfully added!
    </div>
    <a class="btn btn-info mt-3" href="{{ path('product_show', {'id': product.id}) }}" role="button">Show product</a>
    <a class="btn btn-success mt-3" href="{{ path('product_add') }}" role="button">Add more</a>
{% endblock %}

templates/product/access_delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product deleted!{% endblock %}

{% block body %}
    <div class="alert alert-success" role="alert">
        The product "{{ product.title }}" have been deleted!
    </div>
    <a class="mt-3" href="{{ path('product_show_all') }}">Go to the list of products</a>
{% endblock %}

templates/product/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding a Product{% endblock %}

{% block body %}
    <h1>Adding a Product</h1>
    <form method="post" action="{{ path('product_add') }}">
        <div class="form-group">
            <label for="formGroupTitle">Product name</label>
            <input type="text" name="title" class="form-control w-50" id="formGroupTitle" placeholder="Enter a product name">
        </div>
        <div class="form-group">
            <label for="formGroupCategory">Product category</label>
            <select name="id_category" class="form-control w-50" id="formGroupCategory">
                <option value="" class="text-muted">Select a category</option>
                {% if categories %}
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.title }}</option>
                    {% endfor %}
                {% endif %}
            </select>
        </div>
        <div class="form-group">
            <label for="formGroupPrice">Product price</label>
            <input type="number" name="price" class="form-control w-25" id="formGroupPrice" placeholder="Enter a product price">
        </div>
        <div class="form-group">
            <label for="formGroupStock">Product stock</label>
            <input type="number" name="stock" class="form-control w-25" id="formGroupStock" placeholder="Enter a product stock">
        </div>
        <button type="submit" class="btn btn-success mt-3">Add product</button>
    </form>
{% endblock %}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product change{% endblock %}

{% block body %}
    <h1>Product change</h1>
    <form method="post" action="{{ path('product_edit', {'id': product.id}) }}">
        <div class="form-group">
            <label for="formGroupTitle">Product name</label>
            <input type="text" name="title" value="{{ product.title }}" class="form-control w-50" id="formGroupTitle" placeholder="Enter a product name">
        </div>
        <div class="form-group">
            <label for="formGroupCategory">Product category</label>
            <select name="id_category" class="form-control w-50" id="formGroupCategory">
                <option value="" class="text-muted">Select a category</option>
                {% if categories %}
                    {% for category in categories %}
                        <option value="{{ category.id }}"{% if category.id == product.idCategory %} selected{% endif %}>{{ category.title }}</option>
                    {% endfor %}
                {% endif %}
            </select>
        </div>
        <div class="form-group">
            <label for="formGroupPrice">Product price</label>
            <input type="number" name="price" value="{{ product.price }}" class="form-control w-25" id="formGroupPrice" placeholder="Enter a product price">
        </div>
        <div class="form-group">
            <label for="formGroupStock">Product stock</label>
            <input type="number" name="stock" value="{{ product.stock }}" class="form-control w-25" id="formGroupStock" placeholder="Enter a product stock">
        </div>
        <input type="hidden" name="id" value="{{ product.id }}">
        <button type="submit" class="btn btn-success mt-3">Save changes</button>
    </form>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product "{{ product.title }}"{% endblock %}

{% block body %}
    <h1>Product "{{ product.title }}"</h1>
    <div class="mt-3">
        <div><strong>Identifier:</strong> {{ product.id }}</div>
        <div><strong>Title:</strong> {{ product.title }}</div>
        <div><strong>Category:</strong> {{ product.idCategory }}</div>
        <div><strong>Price:</strong> {{ product.price }}</div>
        <div><strong>Stock:</strong> {{ product.stock }}</div>
    </div>
    <div class="mt-3">
        <a class="btn btn-warning" href="{{ path('product_edit', {'id': product.id}) }}" role="button">Edit</a>
        <a class="btn btn-danger" href="{{ path('product_delete', {'id': product.id}) }}" role="button">Delete</a>
    </div>
{% endblock %}

templates/product/show_all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
    <h1>All Products</h1>
    {% if products %}
    <table class="table mt-3">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Actions</th>
        </tr>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.title }}</td>
                <td>{{ product.categoryTitle }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
                <td>
                    <a class="btn btn-info" href="{{ path('product_show', {'id': product.id}) }}" role="button">Show</a>
                    <a class="btn btn-warning" href="{{ path('product_edit', {'id': product.id}) }}" role="button">Edit</a>
                    <a class="btn btn-danger" href="{{ path('product_delete', {'id': product.id}) }}" role="button">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        <p class="mt-3">There are no products yet!</p>
    {% endif %}
    <a class="btn btn-success mt-3" href="{{ path('product_add') }}" role="button">Add product</a>
{% endblock %}